Elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateurs.urls')),         # Inclure les URLs de l'application utilisateurs
    path('programmes/', include('app.urls')),       # Inclure les URLs de l'application principale
    path('api/', include('app.api.urls')),
    
    path('api/users/', include('utilisateurs.api_user.urls')), # Inclure les URLs de l'API

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path,include
from app.views import *
app_name='app'

urlpatterns = [
    # Page d'accueil listant les filières
    path('', ListFiliere.as_view(), name='Filieres'),

    # Cours-related paths
    path('cours/<slug:slug>/', DetailCours.as_view(), name='detail_cours'),
    path('cours/<slug:slug>/modifier/', ModifierCours.as_view(), name='modifier_cours'),
    path('cours/<slug:slug>/supprimer/', ConfirmationSuppressionCours.as_view(), name='SupprimerCours'),
    path('cours/<slug:slug>/annuler/', AnnulerModification.as_view(), name='annuler_modification'),
    path('cours/<slug:cours_slug>/forum/', forum_cours, name='forum_cours'),

    # Créer un cours (lié à filière et matière)
    path('creer-cours/<slug:filiere_slug>/<slug:matiere_slug>/', CreerCours.as_view(), name='CreerCours'),

    # Exercice et devoirs
    path('exercice/<int:exercice_id>/devoirs/', ListeDevoirs.as_view(), name='liste_devoirs'),
    path('devoirs/modifier/<int:devoir_id>/', modifier_devoir, name='modifier_devoir'),
    path('devoirs/supprimer/<int:devoir_id>/', supprimer_devoir, name='supprimer_devoir'),

    # Fonctionnalité de recherche
    path('search/', search, name='search'),

    # Tableau de bord
    path('tableau_de_bord/', tableau_de_bord, name='tableau_de_bord'),

    # Listes des cours d'une filière ou matière
    path('<str:category>/<slug:slug>/', ListCours.as_view(), name='cours'),
    path('<slug:slug>/', ListMatiere.as_view(), name='matiere'),

]

utilisateurs/api_user/urls.py
# api_user/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, ProfileViewSet
from rest_framework.authtoken.views import obtain_auth_token

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)

urlpatterns = [
    path('api-token-auth/', obtain_auth_token),
    path('', include(router.urls)),
    
]

utilisateurs/urls.py
from django.urls import path
from utilisateurs.views import Acceuil,Connexion,Deconnexion,formulaire,forget_password,update_password,confirmation,user_profile,update_profile

urlpatterns =[
    path('', Acceuil,name='Acceuil'),
    path('Connexion', Connexion,name='Connexion'),
    path('Deconnexion', Deconnexion,name='Deconnexion'),
    path('formulaire', formulaire,name='formulaire'),
    path('forget_password', forget_password,name='forget_password'),
    path("update-password/<str:token>/<str:uid>/",update_password,name="update_password" ),
    path('confirmation/<uidb64>/<token>/', confirmation, name='confirmation'),
    path('profile/', user_profile, name='user_profile'),
    path('update_profile/', update_profile, name='update_profile'),

]

utilisateurs/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
import os

# Create your models here.
#logique de rennomage des nom de images que l'utilisateur qura uploader
def Photo_order(instance,filename):
    upload_to='Image/'
    fileExt=filename.split('.')[-1]
    if instance.user.username:
        filename="Photo_order/{}.{}".format(instance.user.username , fileExt)
        return os.path.join(upload_to,filename)
    

class Profile(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    Biographie = models.CharField(max_length=500,blank=True)
    photo =models.ImageField(upload_to=Photo_order,blank=True)


    student = 'student'
    prof = 'prof'
    admin ='admin'

    type_user =[
        (student,'student'),(prof,'prof'),(admin,'admin')
    ]
    type_profile =models.CharField(max_length=200,choices=type_user,default="student")
    
    #recupere le nom de l'utilisateur
    def __str__(self):
        return self.user.username
    

utilisateurs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text="Entrez une adresse email valide.")
    class Meta():
        model = User
        fields =[
            
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]

        def save(self, commit=True):
            user = super(UserForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            if commit:
                user.save()
            return user

class ProfilForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields=[
            "Biographie",
            "photo",
            "type_profile"
        ]

utilisateurs/api_user/views.py
# api_user/views.py
from rest_framework import viewsets
from django.contrib.auth.models import User
from ..models import Profile
from .serializers import UserSerializer, ProfileSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class ProfileViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

utilisateurs/views.py
from django.shortcuts import render,redirect
from .forms import UserForm,ProfilForm
from django.http import HttpResponse, HttpResponseRedirect,HttpResponseForbidden
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.crypto import get_random_string
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
import codecs
from django.shortcuts import get_object_or_404
from .models import Profile


def Acceuil(request):
    try:
        return render(request, 'utilisateurs/Acceuil.html')
    except Exception as e:
        print(f"Erreur : {e}")  # Affiche l'erreur dans la console
        return HttpResponse("Erreur dans le chargement du template.")

def user_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'utilisateurs/user_profile.html', {'profile': profile})


@login_required
def update_profile(request):
    profile = request.user.profile  # Suppose que l'utilisateur a un profil associé
    if request.method == 'POST':
        form = ProfilForm(request.POST, request.FILES, instance=profile)  # Récupère les fichiers uploadés
        if form.is_valid():
            form.save()
            messages.success(request, 'Votre profil a été mis à jour avec succès.')
            return redirect('update_profile')  # Redirige vers une page de profil ou autre
    else:
        form = ProfilForm(instance=profile)  # Pré-remplit le formulaire avec les données existantes
    
    context = {
        'form2': form,
        'inscrit': True,
    }
    return render(request, 'utilisateurs/update_profile.html', context)

def confirmation(request, uidb64, token):
    try:
        # Décoder l'UID
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = get_object_or_404(User, id=uid)

        # Vérifier si le token est valide
        if default_token_generator.check_token(user, token):
            user.is_active = True  # Activer l'utilisateur
            user.save()
            return redirect('Connexion')  # Rediriger vers la page de connexion
        else:
            return render(request, 'utilisateurs/confirmation_invalid.html')  # Token invalide
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    return render(request, 'utilisateurs/confirmation_invalid.html')  # Erreur de confirmation



def formulaire(request):
    inscrit = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profil_form = ProfilForm(data=request.POST)
        
        if user_form.is_valid() and profil_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = False  # L'utilisateur doit confirmer son e-mail avant d'être actif
            user.save()
            
            profil = profil_form.save(commit=False)
            profil.user = user
            profil.save()

            # Générer un token de confirmation
            uid = urlsafe_base64_encode(force_bytes(user.id))
            token = default_token_generator.make_token(user)  # Utiliser le générateur de token par défaut

            # Envoyer l'e-mail de confirmation
            current_site = request.META["HTTP_HOST"]
            context = {
                "token": token,
                "uid": uid,
                "domaine": f"http://{current_site}"
            }
            html_text = render_to_string('utilisateurs/email_confirmation.html', context)
            msg = EmailMessage(
                "Confirmez votre inscription",
                html_text,
                "Elearning <tarnaguedac@gmail.com>",
                [user.email],
            )
            msg.content_subtype = 'html'
            msg.send()
            print(f"Email de confirmation envoyé à {user.email}")

            inscrit = True
            return render(request, 'utilisateurs/confirmation_sent.html')  # Afficher un message à l'utilisateur
        else:
            print(user_form.errors, profil_form.errors)
    else:
        user_form = UserForm()
        profil_form = ProfilForm()

    content = {
        'inscrit': inscrit,
        'form1': user_form,
        'form2': profil_form,
    }
    return render(request, 'utilisateurs/formulaire.html', content)


def Connexion(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # Authentification de l'utilisateur
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                # Connexion réussie
                login(request, user)
                return redirect('/')  # Redirige vers la page d'accueil après connexion
            else:
                return HttpResponse("L'utilisateur est désactivé.")
        else:
            # Si la connexion échoue
            return HttpResponse('Nom d\'utilisateur ou mot de passe incorrect')
    else:
        # Affiche le formulaire de connexion
        return render(request, 'utilisateurs/Connexion.html')
    
@login_required
def Deconnexion (request):
    logout(request)
    return HttpResponseRedirect('/')

def forget_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()

        if user:
            print('envois')
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.id))
            current_site = request.META["HTTP_HOST"]
            context = {"token": token, "uid": uid, "domaine": f"http://{current_site}"}
            html_text=render_to_string('utilisateurs/email.html',context)
            msg = EmailMessage(
                "Réinitialisation de votre mot de passe",
                html_text,
                "Elearning <tarnaguedac@gmail.com>",
                [user.email],
            )
            msg.content_subtype='html'
            msg.send()
            print(f"Email envoyé à {user.email}")
        else:
            print("L'utilisateur n'existe pas.")

    return render(request, 'utilisateurs/forget_password.html', {})


def update_password(request, token, uid):
    try:
        user_id = urlsafe_base64_decode(uid)
        decode_uid = codecs.decode(user_id, "utf-8")
        user = User.objects.get(id=decode_uid)
    except:
        return HttpResponseForbidden(
            "Vous n'aviez pas la permission de modifier ce mot de pass. Utilisateur introuvable"
        )

    check_token = default_token_generator.check_token(user, token)
    if not check_token:
        return HttpResponseForbidden(
            "Vous n'aviez pas la permission de modifier ce mot de pass. Votre Token est invalid ou a espiré"
        )

    error = False
    success = False
    message = ""
    if request.method == "POST":
        password = request.POST.get("password")
        repassword = request.POST.get("repassword")
        print(password, repassword)
        if repassword == password:
            try:
                validate_password(password, user)
                user.set_password(password)
                user.save()

                success = True
                message = "votre mot de pass a été modifié avec succès!"
            except ValidationError as e:
                error = True
                message = str(e)
        else:
            error = True
            message = "Les deux mot de pass ne correspondent pas"

    context = {"error": error, "success": success, "message": message}

    return render(request, "utilisateurs/update_password.html", context)



# Create your views here.

utilisateurs/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning</title>
    <style>
      
      .navbar {
        background-color: rgba(255, 255, 255, 0.25); /* Couleur de fond blanche avec 25% d'opacité */
        backdrop-filter: blur(10px); /* Optionnel : ajoute un effet de flou d'arrière-plan */
    }
    
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">  <!-- Correction de <md-12> en <div class="col-12"> -->
              <nav class="navbar navbar-expand-lg bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Elearning</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'Acceuil' %}">Accueil</a>
                            </li>
            
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'app:tableau_de_bord' %}">Tableau de bord</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Deconnexion' %}">Déconnexion</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'formulaire' %}">Inscription</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Connexion' %}">Connexion</a>
                            </li>
                            {% endif %}
                        </ul>
            
                        <div class="d-flex">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userProfileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userProfileDropdown">
                                    <li><a class="dropdown-item" href="{% url 'user_profile' %}">Mon profil</a></li>
                                    {% if user.is_authenticated %}
                                    <li><a class="dropdown-item" href="{% url 'Deconnexion' %}">Déconnexion</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <form class="d-flex ms-3" method="GET" action="{% url 'app:search' %}">
                                <input class="form-control me-2" type="search" placeholder="Rechercher..." aria-label="Search" name="q">
                                <button class="btn btn-outline-success" type="submit">Rechercher</button>
                            </form>
                        </div>
                    </div>
                </div>
            </nav>
            
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>